name: Make dev release

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      
    - name: Build
      run: |
        export DOTNET_CLI_TELEMETRY_OPTOUT=true
        dotnet build FastMDX -c Release --nologo -o ./build/
        dotnet publish Test -c Release -r win-x64 --nologo --self-contained false -o ./build/Test-Windows-X64
        dotnet publish Test -c Release -r linux-x64 --nologo --self-contained false -o ./build/Test-Linux-X64
        dotnet publish Test -c Release -r osx-x64 --nologo --self-contained false -o ./build/Test-Mac-X64
      
    - name: Pack
      run: |
        cd ./build/
        zip -r9 ./FastMDX-latest.zip ./FastMDX.dll
        zip -r9 ./Test-Windows-X64.zip ./Test-Windows-X64
        zip -r9 ./Test-Linux-X64.zip ./Test-Linux-X64
        zip -r9 ./Test-Mac-X64.zip ./Test-Mac-X64
    
    - name: Upload
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: true
        title: Latest dev build
        files: |
          ./build/FastMDX-latest.zip
          ./build/Test-Windows-X64.zip
          ./build/Test-Linux-X64.zip
          ./build/Test-Mac-X64.zip
